# permissions for end users to edit azureproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: azureprovider-editor-role
rules:
- apiGroups:
  - aegis.aegisproxy.io
  resources:
  - azureproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aegis.aegisproxy.io
  resources:
  - azureproviders/status
  verbs:
  - get
