# permissions for end users to view azureproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: azureprovider-viewer-role
rules:
- apiGroups:
  - aegis.aegisproxy.io
  resources:
  - azureproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aegis.aegisproxy.io
  resources:
  - azureproviders/status
  verbs:
  - get
