# permissions for end users to edit identities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: identity-editor-role
rules:
- apiGroups:
  - aegis.aegisproxy.io
  resources:
  - identities
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aegis.aegisproxy.io
  resources:
  - identities/status
  verbs:
  - get
