# permissions for end users to view ingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: ingress-viewer-role
rules:
- apiGroups:
  - aegis.aegisproxy.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aegis.aegisproxy.io
  resources:
  - ingresses/status
  verbs:
  - get
