# permissions for end users to edit kubernetesproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: kubernetesprovider-editor-role
rules:
- apiGroups:
  - aegis.aegisproxy.io
  resources:
  - kubernetesproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aegis.aegisproxy.io
  resources:
  - kubernetesproviders/status
  verbs:
  - get
